FROM arm32v7/node:8-slim

RUN apt-get update && apt-get install -y \
  bluetooth \
  bluez \
  libbluetooth-dev \
  libudev-dev

RUN npm install sensortag

WORKDIR /app/

COPY package*.json ./





RUN npm install --production

RUN DEBIAN_FRONTEND=noninteractive JOBS=MAX npm install --unsafe-perm

COPY app.js ./

USER node

CMD ["node", "app.js"]
